### ISSUE TITLE
Typo in declared prefix (ark\

### ISSUE THREAD

**Issue by stain** [identifiers-org/cloud-hq-web-frontend#48]
https://registry.identifiers.org/registry/ark says wrongly:

. | .
-- | --
Local Unique Identifier (LUI) pattern | `^(ark\:)/*[0-9A-Za-z]+(?:/[\w/.=*+@\$-]*)?(?:\?.*)?$`
Prefix | `(ark\`
Registry URI | https://registry.identifiers.org/registry/ark
Sample URL | https://identifiers.org/(ark\:/12345/fk1234
Sample Compact identifier | `(ark\:/12345/fk1234`
Sample ID (LUI) | /12345/fk1234

I believe `(ark\` should be `ark` in both `Prefix` and the samples. The sample URL https://identifiers.org/(ark\:/12345/fk1234 does not work.

**Comment by renatocjn** [comment]
Still investigating this one. Seems to be a bug. It seems the registry is correct in the backend, [see](https://registry.api.identifiers.org/restApi/namespaces/1647). Resolutions to the ark prefix also work, [see](http://resolver.api.identifiers.org/ark:/87924/r4154jq8h). 

It may be a frontend issue.

**Comment by renatocjn** [comment]
The issue comes from this namespaceEffectivePrefix here:

https://github.com/identifiers-org/cloud-hq-web-frontend/blob/2108691c0d53725d6771338177208178d4468174/site/src/components/pages/NamespaceDetailsPage.js#L250-L259

This is done when the prefix cannot be case insensitive and must come from the LUI pattern in namespaces where the prefix is embedded in the LUI. I added verification to make sure this effective prefix is still resolvable which is not the case here. This seems to fix the issue, although I think this should be done on the backend. The fix should be pushed to production soon.
